version: 1.0.{build}
image: Visual Studio 2017

cache:
- build/json-src -> CMakeLists.txt, appveyor.yml
- build/assimp-src -> CMakeLists.txt, appveyor.yml
- build/glew-src -> CMakeLists.txt, appveyor.yml
- build/SDL-src -> CMakeLists.txt, appveyor.yml
- build/glm-src -> CMakeLists.txt, appveyor.yml

configuration:
- Debug
- Release
before_build:
- cmd: >-
    if not exist build mkdir build

    cd build

    cmake -G "Visual Studio 15 2017 Win64" ../
build:
  project: build/sp_game.vcxproj
  parallel: true
  verbosity: minimal
artifacts:
- path: build/bin/$(configuration)/sharp_blue.lib
- path: build/bin/$(configuration)/sp_game.exe