version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake -G "Visual Studio 15 2017 Win64" ../
build:
  project: build/sp_game.vcxproj
  parallel: true
  verbosity: minimal
artifacts:
- path: build/bin/$(configuration)/sharp_blue.lib
- path: build/bin/$(configuration)/sp_game.exe